### ISSUE TITLE
Vend Mink-CLI in GOBIN

### ISSUE THREAD

**Issue by ellistarn** [mattmoor/mink#265]
For my projects, I like to maintain a tools module with tools.go and then run 

```
cd tools; GO111MODULE=on cat tools.go | grep _ | awk -F'"' '{print $2}' | xargs -tI % go install %
```
This command should hydrate my environment with all of the tools I need for both development and CI (e.g. Github actions). I'd love to have mink installed using this mechanism.

**Comment by mattmoor** [comment]
Unfortunately the CLI's build process is stupidly complicated, and `go install` and `go get` won't just work today because we use linker options to point it at a variety of images that it should be using for various things.

We could potentially just give these things better defaults, but I feel like your motivations for pinning things is to freeze things, and "better defaults" actually gets you the opposite of that since the images referenced would float forward!

With local builds, what's injected are digests, and releases use release tags, which won't ever move, so I'm not sure how to give you what you *really* want easily.

**Comment by mattmoor** [comment]
Gonna close for now
