### ISSUE TITLE
provide a mechanism to configure image names if using multiple dockerfiles with `mink resolve`

### ISSUE THREAD

**Issue by jstrachan** [mattmoor/mink#279]
if you have a project using multiple `Dockerfile` files in separate folders there does not seem to be a way to use a single top level `mink resolve` and define what images are used for which `dockerfile:///mydir` expression; the image name is taking from the `--image` command line argument.

I wonder if we could use some kind of convention or expression to indicate that the final image name would include the last folder name?

e.g. if you had [this layout](https://github.com/mattmoor/mink/blob/master/APPLY.md) using `Dockerfile` builds in each folder and you ran a single top level. It would could use the folder names (foo/bar/baz) to name the source bundles and the output images via something like:

```bash 
$ mink resolve -f  config --bundle gcr.io/myproject/${DIR}-source --image gcr.io/myproject/${DIR}

generates gcr.io/myproject/foo, gcr.io/myproject/bar, gcr.io/myproject/baz
``` 
so that a single command can make N images with control over the image names used for the source bundles and the final image names; defaulting to the final directory names used?

The other approach could be a YAML file to define all the images inside up front; but I figured something simple like this would give you more control over the image names using a convention-over-configuration style approach?

It would be a minor patch just allowing templating of the `--image` string to be able to include a build-specific expression values?

**Comment by jstrachan** [comment]
the other option which @mattmoor [hinted at in the comments](https://github.com/mattmoor/mink/blob/master/pkg/command/resolve.go#L386) is to provide a path specific configuration file (e.g.  `project.toml` or something) so that path specific configurations can be handled there which may be cleaner

**Comment by mattmoor** [comment]
@jstrachan The original `ko` default was to preserve import paths, so you'd get image names like: `gcr.io/project/knative.dev/serving/cmd/controller`, but unfortunately DockerHub never added support for "directory"-style names.

Over the years, there's been a fair number of "namers" added to `ko`:
1. `-P` to preserve import paths (original default)
2. `(default)` to give `{basename}-{md5 of whole}` variants to mitigate that registry limitation (new default)
3. `-B` to just use `{basename}`
4. `--bare` to just use `KO_DOCKER_REPO` (this is what `mink apply` + `ko publish` uses).  This is also useful with registries like ECR which want you to precreate every repository before pushing.

This sprawl is unfortunate, but each variation serves its purpose.  With `mink`, I sort of gave up and went with the most basic functional variation, though it clearly leaves something to be desired.

---

### A New Hope

While I was adding `4.`, one though was that we could maybe leverage Go templating to both encapsulate these, as well as give users greater control over the way image names are created.  We might consider adopting something like that for `mink`'s `--image` flag (et al).

The basic idea is that we'd have `--image` start to allow Go templates in addition to a static image name.
1. `ghcr.io/mattmoor/images:latest` would still work, it would simply be a template that emits a literal.
2. `ghcr.io/mattmoor/{{.Path}}` (strawman) might be something like `-P`
3. `ghcr.io/mattmoor/{{basename .Path}}` (strawman) might be something like `-B`

I'd love @jonjohnsonjr and @ImJasonH thoughts on this since they've been in the trenches with supporting these options as well, and `ko` could probably use some similar love.

**Comment by jonjohnsonjr** [comment]
I had the same idea but no motivation to implement it: https://github.com/google/ko/issues/44#issuecomment-537590698

This seems totally reasonable to me. I'll keep beating my drum that this shouldn't really be a flag 🙃 

In terms of what object we actually expose to the template, in `ko` we have this subset of `ModulePublic` which would be a good start: https://github.com/google/ko/blob/b84301964af7d03af47949fc9564c79f8ad616a2/pkg/build/gobuild.go#L92-L102

`ModulePublic` has more stuff that might be interesting, especially around versioning and tags... https://golang.org/pkg/cmd/go/internal/modinfo/#ModulePublic

I'm not sure what else people might want to consider in their names, but this seems like a good start. Maybe `time.Now` or `SOURCE_DATE_EPOCH` as well?

At least for a `ko` 1.0, it would be great if this was the only naming mechanism available as user-specific config (perhaps keep the existing flags as hidden aliases for backward compatibility) for simplicity.

**Comment by ImJasonH** [comment]
It's a goal of ko to make container images an invisible implementation detail of your infrastructure. So it's a shame that it has so many options for making those images to comply with all the different image registries' constraints. 😫

Ideally users wouldn't have to care at all about what the images are called, because it doesn't ultimately matter.

As a counterpoint to Go templates to specify image names, what if ko and mink had a heuristic to just guess a valid unique image name for the requested registry? 🤔

**Comment by mattmoor** [comment]
> Ideally users wouldn't have to care at all about what the images are called, because it doesn't ultimately matter.

This is sort of where I landed with mink, which currently says: "YOLO, I'm using digests for everything anyways, so image names are irrelevant!"

What mink does currently works everywhere, which IMO makes it one of the best defaults, but this issue represents a desire to preserve some of that lost information, which I think is valid (after all, I still think `-P` is the best!).

The point of my proposal was that for the simple/common case it is still fairly easy to use correctly everywhere, but the escape hatch enables a significant superset of what `ko` can do without the sprawl of options.



> had a heuristic to just guess a valid unique image name for the requested registry

Anything we do isn't going to be exhaustive, so I think we're going to need an alternative anyways, so this feels like it'd end up being the 15th competing standard since it is insufficient to kill the existing options 😞

**Comment by jstrachan** [comment]
I understand and agree with the idea of hiding the implementation detail of what the actual image name strings are; but unfortunately the use of image registries is complex & we do need a simple escape hatch so that developers can make sure their images fit within whatever infrastructure/policy/RBAC rules they have to comply with.

Whatever we do, we need to specify the registry and owner/project within the registry anyway; so supplying a single string with optional template expressions sounds like a good compromise to me. It still leaves the option open for developers to just specify the registry + owner/project part of the image and use a simple template expression so that mink takes it all from there and does whatever it feels is a good default while still gives developers full control, if they want it, over the exact image string used

**Comment by mattmoor** [comment]
Alright, so I think that I have the mechanics largely in place to achieve this, but I think the remaining question is what information and functions we want to expose for the user to consume.

We should be able to replicate the `ko` behavior simply by passing through the URI-equivalent form for `mink resolve`.

So `mink build --dockerfile=foo/Dockerfile` would get a `url.URL` with `dockerfile:///foo`.

So maybe we could simply start with:
```go
type ImageNameContext struct {
       // Inline the properties of URL, like Scheme, Host, Path
       url.URL
}
```

I'm staging a PR for this now, which folks can take a swing at.

**Comment by mattmoor** [comment]
See what I'm doing in the actions for an idea of the flexibility: https://github.com/mattmoor/mink/pull/301/files#diff-eb7f0a0e6b261bf3ba9adf29ca51f884d195996800ea5194a466bd92138b5f5cR109-R118

**Comment by jonjohnsonjr** [comment]
> `dockerfile:///foo`

Is the triple slash right?

**Comment by mattmoor** [comment]
Yep, file-style URIs.
