### ISSUE TITLE
split mink build Task and TaskRuns

### ISSUE THREAD

**Issue by kameshsampath** [mattmoor/mink#360]
currently the `mink build` command runs builds and runs Tekton `TaskRun`, it will be easy if we define the mink supported Tasks and install it as part of `mink install` and do only TaskRun with *ref* to the related tasks as part of https://github.com/mattmoor/mink/blob/03d30318ffd70d21cd0d3d1e4ca9ab4fec4e784c/pkg/builds/buildpacks/build.go#L81. 

This helps in maintaining the Tasks and TaskRuns

@mattmoor  thoughts ?

**Comment by mattmoor** [comment]
This is effectively what `mink run task` is doing.

If you install `examples/kaniko.yaml` then `mink run task kaniko` == `mink build`.

This morning I plumbed this into `mink resolve` as `task://kaniko?arg=val`.

**Comment by kameshsampath** [comment]
IMHO `mink run task` can be avoided as we try to duplicate what tkn already does via `tkn task start  ...`

**Comment by mattmoor** [comment]
> IMHO mink run task can be avoided as we try to duplicate what tkn already does via tkn task start ...

IMO `mink run task` yields a better devx than `tkn task start` since it builds a `cobra.Command` per task (so you get all of the rich metadata with `--help`, and can pass arguments more naturally.  This is literally why we added these fields 3 years ago 😉

**To be completely clear, it is not my goal to compete with `tkn`!**  Talking to the Tekton CLI WG is on my TODO list, but I wanted to form a more complete picture of how some of the pieces would fit together before raising it there, and a key part of that was finding a way to make the coupling to task definitions looser (`mink run` vs. `mink build`, `task://` vs. `dockerfile://`).

I _have_ mentioned the stuff I've been doing several times in Tekton slack and offered to demo for folks.  I have also given public/recorded demos, which folks from the Tekton community have seen.  But the regular working group time is far too early for me to attend on any regular basis (which I have also mentioned 😉 ).


> Also when doing mink buildpack I don't see we create any TaskDefs

That's because we haven't written `examples/buildpack.yaml` yet, it's on my list.  This may need to be less magical than it is now and use more parameters, but I still need to dig into it.

I think we should probably also link the `kaniko.yaml` (and any others we produce) into the `mink` binary (for use in the inline `TaskRun` spec) so these definitions stay in sync.

> What I mean here is to avoid mink being used to run tasks.

I'm confused by what you mean, since the original comment seemed to be exactly this:

> and do only TaskRun with ref to the related tasks as part of

I completely agree with the goal of providing tasks for what's currently hardcoded.

**Comment by mattmoor** [comment]
shared the kaniko definition a bit more here: https://github.com/mattmoor/mink/pull/361

I've started to clean up the buildpack to do something similar.

**Comment by kameshsampath** [comment]
> I'm confused by what you mean, since the original comment seemed to be exactly this:

I meant "dont want mink to repeat what tkn CLI does". I see your points on devx side of it,  then as you said pushing that to tkn cli would be better option 🤔

**Comment by mattmoor** [comment]
I tagged you on one of the slack threads on this.  Once I know who all to include, I'll try to set something up (likely 2021 at this point).

**Comment by mattmoor** [comment]
I believe this is now done, the task definitions are equivalent in examples/ to what's used internally (they are now produced via `./hack/update-codegen.sh` from the same definition).
